[[redirects]]
  from = "/*"
  to = "https://www.nagpurcranes.in/"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  command = "CI=false npm install --legacy-peer-deps && npm run build"
  publish = "build"

[context.production.environment]
  NODE_ENV = "production"
  NPM_FLAGS = "--legacy-peer-deps"
  CI = "false"
